### ISSUE TITLE
error python -m unittest EmoPy/tests/run_all.py

### ISSUE THREAD

**Issue by Antwnina** [thoughtworksarts/EmoPy#47]
The section with Running tests `python -m unittest EmoPy/tests/run_all.py` gives me this in terminal
```pi@raspberrypi:~ $ ls
Desktop    EmoPy  opencv              opencv.zip  Python-3.6.9         Videos
Documents  MagPi  opencv_contrib      Pictures    Python-3.6.9.tar.xz
Downloads  Music  opencv_contrib.zip  Public      Templates
pi@raspberrypi:~ $ cd EmoPy/
pi@raspberrypi:~/EmoPy $ python -m unittest EmoPy/tests/run_all.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.
pi@raspberrypi:~/EmoPy $ ls
build  EmoPy           LICENSE      readme_docs  requirements.txt
dist   EmoPy.egg-info  MANIFEST.in  README.md    setup.py
pi@raspberrypi:~/EmoPy $ cd EmoPy
pi@raspberrypi:~/EmoPy/EmoPy $ ls
docs  examples  __init__.py  library  models  src  tests
pi@raspberrypi:~/EmoPy/EmoPy $ cd tests
pi@raspberrypi:~/EmoPy/EmoPy/tests $ ls
run_all.py  unittests
pi@raspberrypi:~/EmoPy/EmoPy/tests $ python -m unittest run_all.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "run_all.py", line 1, in <module>
    from EmoPy.tests.unittests.dataloader_test import DataLoaderTest
ImportError: No module named EmoPy.tests.unittests.dataloader_test
pi@raspberrypi:~/EmoPy/EmoPy/tests $ python -m run_all.py
/usr/bin/python: No module named EmoPy.tests.unittests.dataloader_test
pi@raspberrypi:~/EmoPy/EmoPy/tests $ cd ../..
pi@raspberrypi:~/EmoPy $ python -m unittest EmoPy/tests/run_all.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: Import by filename is not supported.```

**Comment by xuv** [comment]
@Antwnina Please use triple ``` to format long code like this. Thank you.

**Comment by Antwnina** [comment]
@xuv done

**Comment by stayrascal** [comment]
@Antwnina Seems that you are using `python2.7` to run tests, how about trying to use `Python3.6` as README.md suggestion.

**Comment by Antwnina** [comment]
@stayrascal I already did that and nothing changed :(

**Comment by cptanalatriste** [comment]
@Antwnina  Can you post an updated stack trace, when using Python 3.6?

**Comment by satishdash** [comment]
@Antwnina  I think this is issue is fixed now with proper version changes in setup.py

**Comment by Antwnina** [comment]
nope still the same... @satishdash @cptanalatriste 
``pi@raspberrypi:~/EmoPy $ sudo python3.6 setup.py install
running install
running bdist_egg
running egg_info
writing EmoPy.egg-info/PKG-INFO
writing dependency_links to EmoPy.egg-info/dependency_links.txt
writing requirements to EmoPy.egg-info/requires.txt
writing top-level names to EmoPy.egg-info/top_level.txt
reading manifest file 'EmoPy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'EmoPy/tests/library/*'
writing manifest file 'EmoPy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/EmoPy
creating build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/dataset.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/data_generator.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/callback.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/directory_data_loader.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/fermodel.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/data_loader.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/neuralnets.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/__init__.py -> build/bdist.linux-armv7l/egg/EmoPy/src
copying build/lib/EmoPy/src/csv_data_loader.py -> build/bdist.linux-armv7l/egg/EmoPy/src
creating build/bdist.linux-armv7l/egg/EmoPy/library
copying build/lib/EmoPy/library/image.py -> build/bdist.linux-armv7l/egg/EmoPy/library
copying build/lib/EmoPy/library/__init__.py -> build/bdist.linux-armv7l/egg/EmoPy/library
creating build/bdist.linux-armv7l/egg/EmoPy/tests
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_empty_data_directory
copying build/lib/EmoPy/tests/unittests/resources/dummy_empty_data_directory/.gitignore -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_empty_data_directory
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_data_directory
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_data_directory/happiness
copying build/lib/EmoPy/tests/unittests/resources/dummy_data_directory/happiness/sample_image.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_data_directory/happiness
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness
creating build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
copying build/lib/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1/sample_image3.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
copying build/lib/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1/sample_image2.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
copying build/lib/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1/sample_image.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
copying build/lib/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1/sample_image5.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
copying build/lib/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1/sample_image4.jpg -> build/bdist.linux-armv7l/egg/EmoPy/tests/unittests/resources/dummy_time_series_data_directory/happiness/sample1
creating build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_145.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_024.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_025.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_0123456.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_145.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_024.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_15.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_036.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_036.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_145.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_02.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_036.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_0256.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_05.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_25.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_05.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_135.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_25.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_156.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_135.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_025.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_026.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_026.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_02.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_0123456.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_012.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_025.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_15.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_05.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_145.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_026.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_01.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_02.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_135.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_156.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_0256.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_0256.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_012.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_156.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_012.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_01.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_024.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_25.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_026.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_135.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_156.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_025.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_0256.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_03.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/__init__.py -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_012.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_model_03.hdf5 -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_036.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_emotion_map_01.json -> build/bdist.linux-armv7l/egg/EmoPy/models
copying build/lib/EmoPy/models/conv_weights_15.h5 -> build/bdist.linux-armv7l/egg/EmoPy/models
creating build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/convolutional_dropout_model.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/fermodel_example.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data
copying build/lib/EmoPy/examples/image_data/sample.csv -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S055_005_00000030.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S074_005_00000034.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S052_004_00000033.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S055_005_00000043.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S074_005_00000043.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
copying build/lib/EmoPy/examples/image_data/sample_image_directory/happiness/S052_004_00000022.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/happiness
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S052_001_00000010.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S055_001_00000009.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S074_002_00000010.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S074_002_00000016.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S052_001_00000015.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
copying build/lib/EmoPy/examples/image_data/sample_image_directory/surprise/S055_001_00000007.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/surprise
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S125_008_00000009.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S113_008_00000016.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S074_004_00000010.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S125_008_00000010.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S113_008_00000019.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_image_directory/anger/S074_004_00000018.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_directory/anger
copying build/lib/EmoPy/examples/image_data/sample_anger_image2.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S074_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S074_004/S074_004_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S074_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S074_004/S074_004_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S074_004
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S111_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S111_007/S111_007_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S111_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S111_007/S111_007_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S111_007
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S130_012
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S130_012/S130_012_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S130_012
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S130_012/S130_012_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S130_012
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S132_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S132_005/S132_005_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S132_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S132_005/S132_005_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S132_005
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S055_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S055_003/S055_003_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S055_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S055_003/S055_003_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S055_003
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S124_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S124_006/S124_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S124_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S124_006/S124_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S124_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S052_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S052_006/S052_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S052_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S052_006/S052_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S052_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S106_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S106_004/S106_004_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S106_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S106_004/S106_004_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S106_004
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S125_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S125_008/S125_008_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S125_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/disgust/S125_008/S125_008_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/disgust/S125_008
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S074_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S074_005/S074_005_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S074_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S074_005/S074_005_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S074_005
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S132_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S132_006/S132_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S132_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S132_006/S132_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S132_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S052_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S052_004/S052_004_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S052_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S052_004/S052_004_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S052_004
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S125_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S125_005/S125_005_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S125_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S125_005/S125_005_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S125_005
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S055_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S055_005/S055_005_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S055_005
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S055_005/S055_005_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S055_005
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S124_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S124_007/S124_007_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S124_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S124_007/S124_007_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S124_007
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S130_013
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S130_013/S130_013_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S130_013
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S130_013/S130_013_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S130_013
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S106_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S106_006/S106_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S106_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/happiness/S106_006/S106_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/happiness/S106_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S125_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S125_007/S125_007_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S125_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S125_007/S125_007_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S125_007
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S055_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S055_001/S055_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S055_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S055_001/S055_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S055_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S052_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S052_001/S052_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S052_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S052_001/S052_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S052_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S074_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S074_002/S074_002_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S074_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S074_002/S074_002_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S074_002
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S113_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S113_001/S113_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S113_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S113_001/S113_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S113_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S124_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S124_001/S124_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S124_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S124_001/S124_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S124_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S111_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S111_001/S111_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S111_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S111_001/S111_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S111_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S130_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S130_001/S130_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S130_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S130_001/S130_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S130_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S132_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S132_008/S132_008_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S132_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/surprise/S132_008/S132_008_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/surprise/S132_008
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S113_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S113_003/S113_003_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S113_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S113_003/S113_003_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S113_003
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S125_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S125_001/S125_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S125_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S125_001/S125_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S125_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S132_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S132_002/S132_002_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S132_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S132_002/S132_002_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S132_002
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S130_009
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S130_009/S130_009_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S130_009
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S130_009/S130_009_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S130_009
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S106_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S106_002/S106_002_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S106_002
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/sadness/S106_002/S106_002_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/sadness/S106_002
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S124_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S124_003/S124_003_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S124_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S124_003/S124_003_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S124_003
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S074_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S074_001/S074_001_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S074_001
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S074_001/S074_001_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S074_001
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S055_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S055_006/S055_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S055_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S055_006/S055_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S055_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S125_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S125_006/S125_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S125_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S125_006/S125_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S125_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S132_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S132_003/S132_003_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S132_003
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/fear/S132_003/S132_003_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/fear/S132_003
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S111_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S111_006/S111_006_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S111_006
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S111_006/S111_006_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S111_006
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S130_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S130_007/S130_007_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S130_007
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S130_007/S130_007_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S130_007
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S113_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S113_008/S113_008_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S113_008
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S113_008/S113_008_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S113_008
creating build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S055_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S055_004/S055_004_00000002.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S055_004
copying build/lib/EmoPy/examples/image_data/sample_image_series_directory/anger/S055_004/S055_004_00000001.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data/sample_image_series_directory/anger/S055_004
copying build/lib/EmoPy/examples/image_data/sample_happy_image.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data
copying build/lib/EmoPy/examples/image_data/sample_disgust_image.png -> build/bdist.linux-armv7l/egg/EmoPy/examples/image_data
copying build/lib/EmoPy/examples/convolutional_model.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/transferlearning_model.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/fermodel_example_webcam.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/convolutional_lstm_model.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/__init__.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/examples/timedelay_conv_model.py -> build/bdist.linux-armv7l/egg/EmoPy/examples
copying build/lib/EmoPy/__init__.py -> build/bdist.linux-armv7l/egg/EmoPy
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/dataset.py to dataset.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/data_generator.py to data_generator.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/callback.py to callback.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/directory_data_loader.py to directory_data_loader.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/fermodel.py to fermodel.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/data_loader.py to data_loader.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/neuralnets.py to neuralnets.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/src/csv_data_loader.py to csv_data_loader.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/library/image.py to image.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/library/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/models/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/convolutional_dropout_model.py to convolutional_dropout_model.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/fermodel_example.py to fermodel_example.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/convolutional_model.py to convolutional_model.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/transferlearning_model.py to transferlearning_model.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/fermodel_example_webcam.py to fermodel_example_webcam.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/convolutional_lstm_model.py to convolutional_lstm_model.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/examples/timedelay_conv_model.py to timedelay_conv_model.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/EmoPy/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying EmoPy.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying EmoPy.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying EmoPy.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying EmoPy.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying EmoPy.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/EmoPy-0.0.5-py3.6.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing EmoPy-0.0.5-py3.6.egg
Removing /usr/local/lib/python3.6/site-packages/EmoPy-0.0.5-py3.6.egg
Copying EmoPy-0.0.5-py3.6.egg to /usr/local/lib/python3.6/site-packages
EmoPy 0.0.5 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/site-packages/EmoPy-0.0.5-py3.6.egg
Processing dependencies for EmoPy==0.0.5
Searching for opencv-python
Reading https://pypi.org/simple/opencv-python/
No local packages or working download links found for opencv-python
error: Could not find suitable distribution for Requirement.parse('opencv-python')
pi@raspberrypi:~/EmoPy $ python3.6 -m unittest EmoPy/tests/run_all.py
Using TensorFlow backend.
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/local/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/local/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/local/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pi/EmoPy/EmoPy/tests/run_all.py", line 2, in <module>
    from EmoPy.tests.unittests.data_generator_test import DataGeneratorTest
  File "/home/pi/EmoPy/EmoPy/tests/unittests/data_generator_test.py", line 5, in <module>
    from EmoPy.src.data_generator import DataGenerator
  File "/home/pi/EmoPy/EmoPy/src/data_generator.py", line 5, in <module>
    K.set_image_dim_ordering('th')
AttributeError: module 'keras.backend' has no attribute `'set_image_dim_ordering'`

**Comment by Antwnina** [comment]
@cptanalatriste  @satishdash 
i also tried to go inside the folder to run the command..
```
pi@raspberrypi:~/EmoPy $ cd EmoPy/tests/
pi@raspberrypi:~/EmoPy/EmoPy/tests $ python3.6 -m unittest run_all.py
Using TensorFlow backend.
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
E
======================================================================
ERROR: run_all (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: run_all
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/pi/EmoPy/EmoPy/tests/run_all.py", line 1, in <module>
    from EmoPy.tests.unittests.dataloader_test import DataLoaderTest
ModuleNotFoundError: No module named 'EmoPy.tests'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by anjutiwari** [comment]
@Antwnina please run the test cases using python3.6 EmoPy/tests/run_all.py

**Comment by microcosm** [comment]
@Antwnina not sure if you are still having an issue here - looks like the request came to an end. Please let us know if there is still a problem, though I would highly encourage you to read and follow the README very closely, and to base your issue requests closely on instructions provided in the README. Also, you might find it most helpful to open only one issue at a time from here on in. We will try to be as responsive as we can, but having a single issue thread will make it easier for people to follow your progress and ultimately help. I hope things worked out for you from here.
